FROM centos

RUN yum install -y java

VOLUME /tmp

ADD /eureka-naming-server-0.0.1-SNAPSHOT.jar eureka-server.jar

RUN sh -c 'touch /eureka-server.jar'

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/eureka-server.jar"]