version: '3'

services:
  
  eureka-server:
    image: itbrijesh143/spring-eureka-server
    restart: always
    ports:
      - 8761:8761
  
  config-server:
    image: itbrijesh143/config-server
    restart: always
    ports:
      - 8888:8888
    depends_on: 
      - eureka-server
